In [2]:
import pandas as pd
import numpy as np

In [4]:
!pip install imbalanced-learn

In [5]:
mel_spec = pd.read_csv("mel_spec.csv",index_col=[0],header=[0,1,2])

In [6]:
genre_track = pd.read_csv("../Data/Clean Data/genre_top_clean.csv")

In [7]:
mel_spec.droplevel([0,1],axis=1)

number           01         02         03         04         05         06  \
track_id                                                                     
2         10.603550  15.770767  30.946888  38.513783  37.899944  17.323717   
3          3.470811  18.241898  21.582163  26.668154  36.802440  13.809479   
5          5.884914   4.027266  19.662582  12.096833  34.823708  17.201840   
10         6.035786  14.539289  23.581905  27.936354  41.786655  35.038370   
134       23.847570  17.565432  26.898178  17.337250  13.567631   6.197043   
...             ...        ...        ...        ...        ...        ...   
155297     6.844879   3.691166   4.433025   2.606051  16.151007  28.388432   
155298    72.488350  20.156069  14.833197  11.717290  16.295730   7.085896   
155306    65.388855  30.388641   5.472199   8.152384  12.737360  19.280369   
155307     1.148585  13.533979  10.286004  16.906560  18.550644  55.698048   
155314    19.166323  16.739994  14.140331   9.052251   3.329178  34.666668   

number           07          08         09         10  ...        90  \
track_id                                               ...             
2         15.564495   13.431223  60.536300  30.692250  ...  0.009084   
3         18.416555   29.319160  24.602644  89.222870  ...  0.019984   
5         11.890505   23.934656  98.253590  59.519370  ...  0.000767   
10        31.030910   21.279102  34.596420  17.227129  ...  0.015715   
134       11.011686   21.329630  68.181240  57.705610  ...  0.005181   
...             ...         ...        ...        ...  ...       ...   
155297     8.532324  100.219210  11.534927  11.195249  ...  0.000011   
155298     8.409733    4.552270  12.455138  36.885290  ...  0.000259   
155306    20.418863   13.152805  25.942500  21.100761  ...  0.001046   
155307    83.554610  125.121445  51.243210  26.477917  ...  0.000732   
155314    48.136337  156.075900  35.392323  30.089409  ...  0.000884   

number          91            92            93            94            95  \
track_id                                                                     
2         0.006577  3.044290e-03  4.101094e-03  1.597607e-03  1.356712e-04   
3         0.014355  1.542818e-02  1.675706e-01  3.438331e-01  2.404508e-01   
5         0.000002  1.876062e-06  1.819358e-06  1.772256e-06  1.731513e-06   
10        0.013018  1.574085e-02  1.001828e-02  8.199858e-03  4.318128e-03   
134       0.000002  1.340112e-07  1.183425e-07  1.068599e-07  9.827019e-08   
...            ...           ...           ...           ...           ...   
155297    0.000009  7.976577e-06  9.510835e-06  8.271507e-06  6.411724e-06   
155298    0.000130  8.079432e-05  9.596386e-05  1.065179e-04  1.116294e-04   
155306    0.000515  4.557871e-04  1.999921e-04  8.703222e-05  2.184795e-05   
155307    0.000211  1.430475e-05  1.544755e-05  4.288732e-06  5.789541e-06   
155314    0.000505  2.079983e-04  1.193272e-04  1.037284e-04  3.839038e-05   

number              96            97            98            99  
track_id                                                          
2         3.260215e-04  5.063414e-05  1.978321e-07  1.936269e-07  
3         1.020738e-02  4.073708e-03  2.258776e-05  4.986430e-07  
5         1.699019e-06  1.671022e-06  1.652220e-06  1.640578e-06  
10        4.747275e-03  4.235102e-03  1.359227e-03  4.363441e-04  
134       9.186782e-08  8.716373e-08  8.382759e-08  8.192676e-08  
...                ...           ...           ...           ...  
155297    4.518870e-06  1.692002e-06  2.310443e-08  2.248148e-08  
155298    9.886256e-05  1.288559e-04  8.976425e-05  5.181448e-05  
155306    6.907134e-06  6.799356e-06  6.720932e-06  6.671471e-06  
155307    1.428207e-05  6.379139e-06  1.784138e-06  2.382824e-06  
155314    1.017161e-05  8.982619e-06  3.012552e-06  1.035641e-06  

[24975 rows x 896 columns]

In [9]:
merged_data = genre_track.merge(mel_spec.droplevel([0,1],axis=1),on="track_id",how="outer").dropna()

In [10]:
merged_data.set_index("track_id",inplace=True)

In [16]:
merged_data

genre_top         01         02         03         04         05  \
track_id                                                                     
2                21  10.603550  15.770767  30.946888  38.513783  37.899944   
3                21   3.470811  18.241898  21.582163  26.668154  36.802440   
5                21   5.884914   4.027266  19.662582  12.096833  34.823708   
10               10   6.035786  14.539289  23.581905  27.936354  41.786655   
134              21  23.847570  17.565432  26.898178  17.337250  13.567631   
...             ...        ...        ...        ...        ...        ...   
155297         1235   6.844879   3.691166   4.433025   2.606051  16.151007   
155298           17  72.488350  20.156069  14.833197  11.717290  16.295730   
155306           17  65.388855  30.388641   5.472199   8.152384  12.737360   
155307           38   1.148585  13.533979  10.286004  16.906560  18.550644   
155314           12  19.166323  16.739994  14.140331   9.052251   3.329178   

                 06         07          08         09  ...        90  \
track_id                                               ...             
2         17.323717  15.564495   13.431223  60.536300  ...  0.009084   
3         13.809479  18.416555   29.319160  24.602644  ...  0.019984   
5         17.201840  11.890505   23.934656  98.253590  ...  0.000767   
10        35.038370  31.030910   21.279102  34.596420  ...  0.015715   
134        6.197043  11.011686   21.329630  68.181240  ...  0.005181   
...             ...        ...         ...        ...  ...       ...   
155297    28.388432   8.532324  100.219210  11.534927  ...  0.000011   
155298     7.085896   8.409733    4.552270  12.455138  ...  0.000259   
155306    19.280369  20.418863   13.152805  25.942500  ...  0.001046   
155307    55.698048  83.554610  125.121445  51.243210  ...  0.000732   
155314    34.666668  48.136337  156.075900  35.392323  ...  0.000884   

                91            92            93            94            95  \
track_id                                                                     
2         0.006577  3.044290e-03  4.101094e-03  1.597607e-03  1.356712e-04   
3         0.014355  1.542818e-02  1.675706e-01  3.438331e-01  2.404508e-01   
5         0.000002  1.876062e-06  1.819358e-06  1.772256e-06  1.731513e-06   
10        0.013018  1.574085e-02  1.001828e-02  8.199858e-03  4.318128e-03   
134       0.000002  1.340112e-07  1.183425e-07  1.068599e-07  9.827019e-08   
...            ...           ...           ...           ...           ...   
155297    0.000009  7.976577e-06  9.510835e-06  8.271507e-06  6.411724e-06   
155298    0.000130  8.079432e-05  9.596386e-05  1.065179e-04  1.116294e-04   
155306    0.000515  4.557871e-04  1.999921e-04  8.703222e-05  2.184795e-05   
155307    0.000211  1.430475e-05  1.544755e-05  4.288732e-06  5.789541e-06   
155314    0.000505  2.079983e-04  1.193272e-04  1.037284e-04  3.839038e-05   

                    96            97            98            99  
track_id                                                          
2         3.260215e-04  5.063414e-05  1.978321e-07  1.936269e-07  
3         1.020738e-02  4.073708e-03  2.258776e-05  4.986430e-07  
5         1.699019e-06  1.671022e-06  1.652220e-06  1.640578e-06  
10        4.747275e-03  4.235102e-03  1.359227e-03  4.363441e-04  
134       9.186782e-08  8.716373e-08  8.382759e-08  8.192676e-08  
...                ...           ...           ...           ...  
155297    4.518870e-06  1.692002e-06  2.310443e-08  2.248148e-08  
155298    9.886256e-05  1.288559e-04  8.976425e-05  5.181448e-05  
155306    6.907134e-06  6.799356e-06  6.720932e-06  6.671471e-06  
155307    1.428207e-05  6.379139e-06  1.784138e-06  2.382824e-06  
155314    1.017161e-05  8.982619e-06  3.012552e-06  1.035641e-06  

[24975 rows x 897 columns]

In [18]:
mel_spec.columns

MultiIndex([('mel_spec', 'kurtosis', '01'),
            ('mel_spec', 'kurtosis', '02'),
            ('mel_spec', 'kurtosis', '03'),
            ('mel_spec', 'kurtosis', '04'),
            ('mel_spec', 'kurtosis', '05'),
            ('mel_spec', 'kurtosis', '06'),
            ('mel_spec', 'kurtosis', '07'),
            ('mel_spec', 'kurtosis', '08'),
            ('mel_spec', 'kurtosis', '09'),
            ('mel_spec', 'kurtosis', '10'),
            ...
            ('mel_spec',      'std', '90'),
            ('mel_spec',      'std', '91'),
            ('mel_spec',      'std', '92'),
            ('mel_spec',      'std', '93'),
            ('mel_spec',      'std', '94'),
            ('mel_spec',      'std', '95'),
            ('mel_spec',      'std', '96'),
            ('mel_spec',      'std', '97'),
            ('mel_spec',      'std', '98'),
            ('mel_spec',      'std', '99')],
           names=['feature', 'statistics', 'number'], length=896)

In [20]:
merged_data.columns = pd.MultiIndex.from_tuples([('gerne_top','','')]+mel_spec.columns.tolist())

In [22]:
merged_data = merged_data.replace([np.inf, -np.inf], np.nan)

In [24]:
merged_data.dropna(inplace=True)

In [26]:
track_echonest_feature_clean = pd.read_csv("../Data/Clean Data/track_echonest_feature_clean.csv",index_col=[0,1],header=[0,1,2])

In [28]:
track_echonest_feature_clean.drop('echonest',axis=1,inplace=True)

/var/folders/gv/571nb6gs4h58lv0gw0__gy280000gn/T/ipykernel_22411/3215259182.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  track_echonest_feature_clean.drop('echonest',axis=1,inplace=True)


In [30]:
merged_data.drop('gerne_top',axis=1)

mel_spec                                                         \
           kurtosis                                                          
                 01         02         03         04         05         06   
track_id                                                                     
2         10.603550  15.770767  30.946888  38.513783  37.899944  17.323717   
3          3.470811  18.241898  21.582163  26.668154  36.802440  13.809479   
5          5.884914   4.027266  19.662582  12.096833  34.823708  17.201840   
10         6.035786  14.539289  23.581905  27.936354  41.786655  35.038370   
134       23.847570  17.565432  26.898178  17.337250  13.567631   6.197043   
...             ...        ...        ...        ...        ...        ...   
155297     6.844879   3.691166   4.433025   2.606051  16.151007  28.388432   
155298    72.488350  20.156069  14.833197  11.717290  16.295730   7.085896   
155306    65.388855  30.388641   5.472199   8.152384  12.737360  19.280369   
155307     1.148585  13.533979  10.286004  16.906560  18.550644  55.698048   
155314    19.166323  16.739994  14.140331   9.052251   3.329178  34.666668   

                                                       ...            \
                                                       ...       std   
                 07          08         09         10  ...        90   
track_id                                               ...             
2         15.564495   13.431223  60.536300  30.692250  ...  0.009084   
3         18.416555   29.319160  24.602644  89.222870  ...  0.019984   
5         11.890505   23.934656  98.253590  59.519370  ...  0.000767   
10        31.030910   21.279102  34.596420  17.227129  ...  0.015715   
134       11.011686   21.329630  68.181240  57.705610  ...  0.005181   
...             ...         ...        ...        ...  ...       ...   
155297     8.532324  100.219210  11.534927  11.195249  ...  0.000011   
155298     8.409733    4.552270  12.455138  36.885290  ...  0.000259   
155306    20.418863   13.152805  25.942500  21.100761  ...  0.001046   
155307    83.554610  125.121445  51.243210  26.477917  ...  0.000732   
155314    48.136337  156.075900  35.392323  30.089409  ...  0.000884   

                                                                            \
                                                                             
                91            92            93            94            95   
track_id                                                                     
2         0.006577  3.044290e-03  4.101094e-03  1.597607e-03  1.356712e-04   
3         0.014355  1.542818e-02  1.675706e-01  3.438331e-01  2.404508e-01   
5         0.000002  1.876062e-06  1.819358e-06  1.772256e-06  1.731513e-06   
10        0.013018  1.574085e-02  1.001828e-02  8.199858e-03  4.318128e-03   
134       0.000002  1.340112e-07  1.183425e-07  1.068599e-07  9.827019e-08   
...            ...           ...           ...           ...           ...   
155297    0.000009  7.976577e-06  9.510835e-06  8.271507e-06  6.411724e-06   
155298    0.000130  8.079432e-05  9.596386e-05  1.065179e-04  1.116294e-04   
155306    0.000515  4.557871e-04  1.999921e-04  8.703222e-05  2.184795e-05   
155307    0.000211  1.430475e-05  1.544755e-05  4.288732e-06  5.789541e-06   
155314    0.000505  2.079983e-04  1.193272e-04  1.037284e-04  3.839038e-05   

                                                                  
                                                                  
                    96            97            98            99  
track_id                                                          
2         3.260215e-04  5.063414e-05  1.978321e-07  1.936269e-07  
3         1.020738e-02  4.073708e-03  2.258776e-05  4.986430e-07  
5         1.699019e-06  1.671022e-06  1.652220e-06  1.640578e-06  
10        4.747275e-03  4.235102e-03  1.359227e-03  4.363441e-04  
134       9.186782e-08  8.716373e-08  8.382759e-08  

In [35]:
onlySmallTid = pd.read_csv("onlySmallTid.csv")

In [41]:
onlySmallTid

Unnamed: 0  track_id
0              0         2
1              1         5
2              2        10
3              3       140
4              4       141
...          ...       ...
7995        7995    154308
7996        7996    154309
7997        7997    154413
7998        7998    154414
7999        7999    155066

[8000 rows x 2 columns]

In [32]:
features_inc_mel_spec = track_echonest_feature_clean.reset_index().merge(merged_data.drop('gerne_top',axis=1),on="track_id")

In [400]:
selected_features_inc_mel_spec= features_inc_mel_spec[features_inc_mel_spec["genre_top"].isin([15,12,10,17,25,1,21,32,107,76,41,27,18,42,66])]

In [402]:
selected_features_inc_mel_spec["genre_top"].value_counts()

genre_top
12    1844
15    1384
21     530
17     427
10     231
Name: count, dtype: int64

In [404]:
selected_features_inc_mel_spec['genre_top']

0       21
1       21
2       21
3       10
4       21
        ..
5271    12
5272    12
5274    12
5275    12
5276    12
Name: genre_top, Length: 4416, dtype: int64

In [75]:
onlySmall = features_inc_mel_spec[features_inc_mel_spec["track_id"].isin(onlySmallTid["track_id"].tolist())].dropna()

In [77]:
X= onlySmall.drop(['track_id','genre_top'],axis=1)
y = onlySmall['genre_top']

/var/folders/gv/571nb6gs4h58lv0gw0__gy280000gn/T/ipykernel_22411/1376589711.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  X= onlySmall.drop(['track_id','genre_top'],axis=1)


In [408]:
track_echonest_feature_clean.reset_index().columns

MultiIndex([(   'track_id',         '',   ''),
            (  'genre_top',         '',   ''),
            ('chroma_cens', 'kurtosis', '01'),
            ('chroma_cens', 'kurtosis', '02'),
            ('chroma_cens', 'kurtosis', '03'),
            ('chroma_cens', 'kurtosis', '04'),
            ('chroma_cens', 'kurtosis', '05'),
            ('chroma_cens', 'kurtosis', '06'),
            ('chroma_cens', 'kurtosis', '07'),
            ('chroma_cens', 'kurtosis', '08'),
            ...
            (    'tonnetz',      'std', '04'),
            (    'tonnetz',      'std', '05'),
            (    'tonnetz',      'std', '06'),
            (        'zcr', 'kurtosis', '01'),
            (        'zcr',      'max', '01'),
            (        'zcr',     'mean', '01'),
            (        'zcr',   'median', '01'),
            (        'zcr',      'min', '01'),
            (        'zcr',     'skew', '01'),
            (        'zcr',      'std', '01')],
           length=520)

In [99]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [606]:
from imblearn.over_sampling import SMOTE

In [101]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [610]:
smote = SMOTE(sampling_strategy='auto', random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(x_train, y_train)

In [103]:
model = RandomForestClassifier(n_estimators = 100)

In [105]:
model.fit(x_train,y_train)

RandomForestClassifier()

In [106]:
y_pred = model.predict(x_test)

In [109]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred,average='micro')
recall = recall_score(y_test, y_pred,average='micro')
f1 = f1_score(y_test, y_pred,average='micro')
confusion = confusion_matrix(y_test, y_pred)
mean_squared_error = mean_squared_error(y_test, y_pred)
r2_score = r2_score(y_test, y_pred)


# Print metricsµ
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")
print(f"Confusion Matrix:\n{confusion}")
print(f"Mean Squared Error: {mean_squared_error}")
print(f"R2 Score: {r2_score}")

Accuracy: 0.6332046332046332
Precision: 0.6332046332046332
Recall: 0.6332046332046332
F1-score: 0.6332046332046332
Confusion Matrix:
[[10  1  0  0  4  3  0  0]
 [ 2 20  3  1  8  9  0  0]
 [ 1  6 32  0  5  6  0  0]
 [ 0  1  3  9  1 17  0  0]
 [ 0  7  4  0 54  1  0  0]
 [ 0  0  3  0  1 37  0  0]
 [ 0  1  1  0  1  0  0  0]
 [ 0  1  1  0  3  0  0  2]]
Mean Squared Error: 28782.397683397685
R2 Score: 0.2659170768584932


In [111]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           2       0.77      0.56      0.65        18
          10       0.54      0.47      0.50        43
          12       0.68      0.64      0.66        50
          15       0.90      0.29      0.44        31
          17       0.70      0.82      0.76        66
          21       0.51      0.90      0.65        41
          38       0.00      0.00      0.00         3
        1235       1.00      0.29      0.44         7

    accuracy                           0.63       259
   macro avg       0.64      0.49      0.51       259
weighted avg       0.67      0.63      0.61       259



/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [618]:
mona_lisa = pd.read_csv("mona_lisa.csv",index_col=[0],header=[0,1,2])

In [619]:
mona_lisa['mel_spec']

statistics  kurtosis                                                      \
number            01         02         03        04        05        06   
0          -0.638501  17.332769  18.986349  15.19903  5.498353  5.003734   

statistics                                             ...       std  \
number            07         08         09         10  ...        90   
0           8.439813  20.058945  14.515284  13.989283  ...  0.000749   

statistics                                                             \
number            91        92        93        94       95        96   
0           0.000736  0.000727  0.000727  0.000721  0.00069  0.000675   

statistics                                
number            97        98        99  
0           0.000677  0.000669  0.000666  

[1 rows x 896 columns]

In [653]:
model.predict(mona_lisa)

array([15])